/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/babagift_compressed.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/babagift_compressed.glb')
  return (
    <group {...props} dispose={null}>
      {/* <pointLight intensity={54351.413} decay={2} position={[4.076, 5.56, -1.005]} rotation={[-1.839, 0.602, 1.932]} /> */}
      {/* <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={32.526} position={[9.564, 3.351, -44.145]} rotation={[-1.485, 1.433, 1.485]} /> */}
      <mesh geometry={nodes.maple_character.geometry} material={materials.maple_character} position={[0.022, 0.598, 3.425]} rotation={[1.57, 0.001, -1.563]} />
      <mesh geometry={nodes.background.geometry} material={materials['Material.002']} position={[-1.009, 2.83, -27.535]} rotation={[0, 0, -Math.PI / 2]} scale={[5.705, 1, 34.762]} />
      <mesh geometry={nodes.mapletree.geometry} material={materials.mapletree} position={[-0.403, 0.835, 0.813]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.165} />
      <mesh geometry={nodes.mapletree001.geometry} material={materials.mapletree} position={[0.828, 0.882, -0.793]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.165} />
      <mesh geometry={nodes.mapletree002.geometry} material={materials.mapletree} position={[-0.403, 0.825, -2.263]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.165} />
      <mesh geometry={nodes.bike_seat.geometry} material={materials.bike_seat} position={[0, 0.305, 3.329]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.bikewheel_back.geometry} material={materials.bikewheel_back} position={[0.022, 0.139, 3.693]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.634} />
      <mesh geometry={nodes.bikewheel_front.geometry} material={materials.bikewheel_front} position={[0.064, 0.107, 2.954]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.686} />
      <mesh geometry={nodes.Grass.geometry} material={materials['Material.003']} position={[0.014, -0.037, -1.859]} scale={[1, 1, 7.725]} />
      <mesh geometry={nodes.grass.geometry} material={materials.grass} position={[-0.433, 0.198, 1.793]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.717} />
      <mesh geometry={nodes.grass001.geometry} material={materials.grass} position={[-0.506, 0.198, -0.607]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.717} />
      <mesh geometry={nodes.grass002.geometry} material={materials.grass} position={[0.588, 0.198, 1.182]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.717} />
      <mesh geometry={nodes.grass003.geometry} material={materials.grass} position={[0.509, 0.198, -1.183]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.717} />
      <mesh geometry={nodes.grass004.geometry} material={materials.grass} position={[0.509, 0.198, 4.349]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.717} />
      <mesh geometry={nodes.grass005.geometry} material={materials.grass} position={[0.509, 0.198, -7.103]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.717} />
      <mesh geometry={nodes.grass006.geometry} material={materials.grass} position={[-0.473, 0.198, -9.466]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.717} />
      <mesh geometry={nodes.grass007.geometry} material={materials.grass} position={[-0.427, 0.198, -7.658]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.717} />
      <mesh geometry={nodes.grass008.geometry} material={materials.grass} position={[0.509, 0.198, -2.855]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.717} />
      <mesh geometry={nodes.grass009.geometry} material={materials.grass} position={[-0.272, 0.198, -3.257]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.717} />
      <mesh geometry={nodes.badminton.geometry} material={materials.badminton} position={[0.592, 0.099, -5.74]} rotation={[1.521, 0.002, -1.575]} scale={0.665} />
      <mesh geometry={nodes.cloud.geometry} material={materials.cloud} position={[-0.677, 2.088, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-1.268, -2.989, -1.13]} />
      <mesh geometry={nodes.cloud001.geometry} material={materials.cloud} position={[-0.617, 2.446, -1.465]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.139, 1, 1.038]} />
      <mesh geometry={nodes.cloud002.geometry} material={materials.cloud} position={[-0.679, 2.056, -8.524]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.139, 1, 1.038]} />
      <mesh geometry={nodes.cloud003.geometry} material={materials.cloud} position={[-0.679, 1.738, -10.731]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.273, 1.118, 1.16]} />
      <mesh geometry={nodes.cloud004.geometry} material={materials.cloud} position={[-0.679, 1.942, -16.928]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.273, 1.118, 1.16]} />
      <mesh geometry={nodes.cloud005.geometry} material={materials.cloud} position={[1.141, 1.973, -17.311]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.534, 1.347, 1.398]} />
      <mesh geometry={nodes.cloud006.geometry} material={materials.cloud} position={[0.834, 1.764, -11.637]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.611, 1.415, 1.468]} />
      <mesh geometry={nodes.cloud008.geometry} material={materials.cloud} position={[-0.089, 5.596, -26.643]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.219, 1.071, 1.111]} />
      <mesh geometry={nodes.cloud009.geometry} material={materials.cloud} position={[-0.745, 5.096, -23.8]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.087, 0.955, 0.991]} />
      <mesh geometry={nodes.fathersday.geometry} material={materials.fathersday} position={[-0.979, 1.871, 4.309]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.596} />
      <mesh geometry={nodes.flower.geometry} material={materials.flower} position={[-0.632, 0.194, -0.478]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.531} />
      <mesh geometry={nodes.flower001.geometry} material={materials.flower} position={[0.802, 0.194, 1.469]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.531} />
      <mesh geometry={nodes.flower002.geometry} material={materials.flower} position={[0.389, 0.194, -3.004]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.531} />
      <mesh geometry={nodes.flower003.geometry} material={materials.flower} position={[0.488, 0.194, -7.344]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.531} />
      <mesh geometry={nodes.house.geometry} material={materials.house} position={[-0.14, 0.695, -5.684]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={3.202} />
      <mesh geometry={nodes.normaltree.geometry} material={materials.normaltree} position={[-0.541, 0.777, -7.467]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.937} />
      <mesh geometry={nodes.normaltree001.geometry} material={materials.normaltree} position={[0.827, 0.777, -8.554]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.937} />
      <mesh geometry={nodes.paragraph.geometry} material={materials.paragraph} position={[-0.955, 0.975, 3.021]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.605} />
      <mesh geometry={nodes.photo1.geometry} material={materials.photo1} position={[-0.686, 2.36, -4.335]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.94} />
      <mesh geometry={nodes.photo2.geometry} material={materials.photo2} position={[-0.605, 2.154, -5.582]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.562} />
      <mesh geometry={nodes.photo3.geometry} material={materials.photo3} position={[-0.652, 2.505, -7.001]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.851} />
      <mesh geometry={nodes.picnic_blanket.geometry} material={materials.picnic_blanket} position={[0.689, 0.025, -4.885]} rotation={[Math.PI / 2, 1.515, -Math.PI / 2]} scale={[1.418, 0.482, 1.537]} />
      <mesh geometry={nodes.picnic_blanket001.geometry} material={materials.picnic_blanket} position={[0.689, 0.359, -20.966]} rotation={[-3.08, 1.474, -2.66]} scale={[1.418, 0.482, 1.537]} />
      <mesh geometry={nodes.picnic_people.geometry} material={materials.picnic_people} position={[0.824, 0.356, -4.962]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.32} />
      <mesh geometry={nodes.postit1.geometry} material={materials.postit1} position={[-0.944, 1.793, 1.937]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.postit2.geometry} material={materials.postit2} position={[-0.947, 2.149, 2.773]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.soccer.geometry} material={materials.soccer} position={[0.882, 0.07, -5.942]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.351} />
      <mesh geometry={nodes.stick.geometry} material={materials['Material.001']} position={[-0.074, -0.231, 3.339]} scale={[0.016, 0.581, 0.016]} />
      <mesh geometry={nodes.string.geometry} material={materials.string} position={[-0.732, 3.483, -4.311]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.string001.geometry} material={materials.string} position={[-0.732, 3.437, -5.595]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.string002.geometry} material={materials.string} position={[-0.732, 3.53, -7.03]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.string003.geometry} material={materials.string} position={[-0.536, 6.567, -12.312]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[3.441, 1, 1]} />
      <mesh geometry={nodes.string004.geometry} material={materials.string} position={[-0.621, 6.291, -14.257]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[3.012, 1, 1]} />
      <mesh geometry={nodes.string005.geometry} material={materials.string} position={[-0.854, 6.209, -16.194]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[3.623, 1, 1]} />
      <mesh geometry={nodes.string006.geometry} material={materials.string} position={[0.306, 6.285, -17.296]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[3.288, 1, 1]} />
      <mesh geometry={nodes.string007.geometry} material={materials.string} position={[-0.933, 5.298, -21.652]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[2.962, 1, 1]} />
      <mesh geometry={nodes.string008.geometry} material={materials.string} position={[-0.933, 5.552, -23.448]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[2.61, 1, 1]} />
      <mesh geometry={nodes.string009.geometry} material={materials.string} position={[-0.461, 6.324, -29.818]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[2.29, 1, 1]} />
      <mesh geometry={nodes.string010.geometry} material={materials.string} position={[-0.461, 6.68, -30.588]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[2.254, 1, 1]} />
      <mesh geometry={nodes.string011.geometry} material={materials.string} position={[-0.604, 6.253, -31.278]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[2.625, 1, 1]} />
      <mesh geometry={nodes.string012.geometry} material={materials.string} position={[-0.203, 2.744, -38.475]} rotation={[-2.159, 0, -Math.PI / 2]} scale={[4.359, 1, 1.252]} />
      <mesh geometry={nodes.string013.geometry} material={materials.string} position={[-0.888, 7.706, -36.678]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[2.625, 1, 1]} />
      <mesh geometry={nodes.string014.geometry} material={materials.string} position={[-0.225, 6.518, -38.076]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[2.625, 1, 1]} />
      <mesh geometry={nodes.hobbies.geometry} material={materials.hobbies} position={[-0.905, 0.519, -4.231]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.518} />
      <mesh geometry={nodes.Ocean.geometry} material={materials['Material.003']} position={[0.01, -0.022, -10.768]} scale={[1, 1, 1.146]} />
      <mesh geometry={nodes.dolphin.geometry} material={materials.dolphin} position={[-0.331, 0, -17.819]} rotation={[1.398, 0, -Math.PI / 2]} scale={2.078} />
      <mesh geometry={nodes.wave.geometry} material={materials.wave} position={[0, 0.136, -11.266]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.612} />
      <mesh geometry={nodes.wave001.geometry} material={materials.wave} position={[0, 0.049, -13.7]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.612} />
      <mesh geometry={nodes.wave002.geometry} material={materials.wave} position={[0, 0.031, -16.195]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.612} />
      <mesh geometry={nodes.wave003.geometry} material={materials.wave} position={[0, 0.085, -19.452]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.612} />
      <mesh geometry={nodes.airplane.geometry} material={materials.airplane} position={[0.232, 2.475, -13.761]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.793} />
      <mesh geometry={nodes.birds.geometry} material={materials.birds} position={[1.183, 1.566, -15.479]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.birds001.geometry} material={materials.birds} position={[-0.646, 2.39, -18.913]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.photo6.geometry} material={materials.photo6} position={[-0.751, 2.882, -16.096]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.45} />
      <mesh geometry={nodes.photo7.geometry} material={materials.photo7} position={[0.35, 3.302, -17.294]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.22} />
      <mesh geometry={nodes.photo5.geometry} material={materials.photo5} position={[-0.47, 3.175, -12.298]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.22} />
      <mesh geometry={nodes.photo4.geometry} material={materials.photo4} position={[-0.516, 3.405, -14.314]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.22} />
      <mesh geometry={nodes.travelquote2.geometry} material={materials.travelquote2} position={[-0.793, 0.835, -14.526]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.336} />
      <mesh geometry={nodes.travelquote1.geometry} material={materials.travelquote1} position={[-0.922, 2.124, -10.959]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.698} />
      <mesh geometry={nodes.Beach.geometry} material={materials['Material.003']} position={[0, 0, -20.661]} scale={[1, 1, 0.274]} />
      <mesh geometry={nodes.beachumbrella.geometry} material={materials.beachumbrella} position={[0.939, 1.007, -21.219]} rotation={[1.802, 0.044, -1.591]} scale={1.324} />
      <mesh geometry={nodes.sand_castle.geometry} material={materials.sand_castle} position={[-0.826, 0.788, -21.02]} rotation={[2.077, 0.026, -1.711]} scale={1.506} />
      <mesh geometry={nodes.mom.geometry} material={materials.mom} position={[0.598, 0.577, -20.936]} rotation={[2.015, 0.091, -1.682]} />
      <mesh geometry={nodes.maple_chloe.geometry} material={materials.maple_chloe} position={[-0.438, 0.547, -20.778]} rotation={[2.036, -0.005, -1.643]} scale={0.817} />
      <mesh geometry={nodes.motercycle.geometry} material={materials.motercycle} position={[0, 1.426, -23.319]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.151} />
      <mesh geometry={nodes.motercycle_wheel.geometry} material={materials.motercycle_wheel} position={[0.037, 1.133, -23.808]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.443} />
      <mesh geometry={nodes.motercycle_wheel001.geometry} material={materials.motercycle_wheel} position={[0.037, 1.121, -22.977]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.479} />
      <mesh geometry={nodes.Ocean001.geometry} material={materials['Material.003']} position={[0, 1.1, -23.444]} scale={[1, 1, 1.146]} />
      <mesh geometry={nodes.photo8.geometry} material={materials.photo8} position={[-0.915, 2.86, -23.33]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.997} />
      <mesh geometry={nodes.photo11.geometry} material={materials.photo11} position={[-0.428, 4.127, -29.805]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.087} />
      <mesh geometry={nodes.photo10.geometry} material={materials.photo10} position={[-0.427, 4.696, -30.615]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.087} />
      <mesh geometry={nodes.photo12.geometry} material={materials.photo12} position={[-0.78, 2.414, -21.578]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.942} />
      <mesh geometry={nodes.photo9.geometry} material={materials.photo9} position={[-0.53, 3.705, -31.304]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.326} />
      <mesh geometry={nodes.foodquote.geometry} material={materials.foodquote} position={[-0.813, 1.042, -19.716]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.802} />
      <mesh geometry={nodes.cookingquote.geometry} material={materials.cookingquote} position={[-0.9, 2.321, -30.712]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.758} />
      <mesh geometry={nodes.buildingon_poster.geometry} material={materials.buildingone45149} position={[-0.915, 2.04, -25.946]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.028, 0.581, 1.26]} />
      <mesh geometry={nodes.buildingone_back.geometry} material={materials.buildingone43643} position={[-0.96, 2.302, -25.288]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.33, 3.735, 3.188]} />
      <mesh geometry={nodes.buildingone_board.geometry} material={materials.buildingone43718} position={[-0.904, 2.25, -25.081]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.618, 0.769, 1.523]} />
      <mesh geometry={nodes.buildingone_floor.geometry} material={materials.buildingone44923} position={[-0.615, 1.189, -25.287]} rotation={[Math.PI / 2, 1.508, -Math.PI / 2]} scale={[2.428, 2.97, 1.378]} />
      <mesh geometry={nodes.buildingone_greenbottom.geometry} material={materials.buildingone44817} position={[0.174, 2.649, -25.24]} rotation={[1.546, 0.002, -1.566]} scale={[2.431, 0.984, 2.137]} />
      <mesh geometry={nodes.buildingone_greentop.geometry} material={materials.buildingone44812} position={[0.362, 2.823, -25.234]} rotation={[1.609, 1.079, -1.621]} scale={[2.397, 1.89, 1.238]} />
      <mesh geometry={nodes.buildingone_name.geometry} material={materials.buildingone43027} position={[-0.077, 2.532, -25.292]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.039, 0.916, 1.988]} />
      <mesh geometry={nodes.buildingone_noodels.geometry} material={materials.buildingone44452} position={[0.885, 1.568, -26.112]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.77, 1, 1.402]} />
      <mesh geometry={nodes.buildingone_noodels001.geometry} material={materials.buildingone44452} position={[-0.796, 1.568, -23.607]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.77, 1, 1.402]} />
      <mesh geometry={nodes.buildingone_redroot1.geometry} material={materials.buildingone43210} position={[0.003, 3.243, -25.321]} rotation={[1.577, 1.002, -1.573]} scale={[2.133, 1.805, 1.313]} />
      <mesh geometry={nodes.buildingone_redsign.geometry} material={materials.buildingone44539} position={[-0.223, 1.421, -25.05]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.118, 1, 1.546]} />
      <mesh geometry={nodes.buildingone_side.geometry} material={materials.buildingone43528} position={[-0.637, 2.283, -26.211]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1, 1.77, 2.692]} />
      <mesh geometry={nodes.buildingone_side001.geometry} material={materials.buildingone43417} position={[-0.602, 2.208, -24.42]} rotation={[1.547, 0.01, 0.038]} scale={[1.001, 1.768, 2.545]} />
      <mesh geometry={nodes.buildingone_soup.geometry} material={materials.buildingone43945} position={[-0.318, 1.899, -24.965]} rotation={[Math.PI / 2, 1.409, -Math.PI / 2]} scale={[1.57, 1.389, 0.808]} />
      <mesh geometry={nodes.buildingone_table.geometry} material={materials.buildingone44117} position={[0.788, 1.505, -26.179]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.77, 1, 1.695]} />
      <mesh geometry={nodes.buildingone_table001.geometry} material={materials.buildingone44117} position={[-0.832, 1.505, -23.616]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.77, 1, 1.695]} />
      <mesh geometry={nodes.buildingone_top.geometry} material={materials.buildingone43210} position={[-0.328, 3.533, -25.352]} rotation={[Math.PI / 2, 1.394, -Math.PI / 2]} scale={[2.16, 2.163, 1.446]} />
      <mesh geometry={nodes.buildingone_top001.geometry} material={materials.buildingone43210} position={[-0.677, 4.688, -25.352]} rotation={[Math.PI / 2, 0.288, -Math.PI / 2]} scale={[2.073, 2.129, 1.161]} />
      <mesh geometry={nodes.ice_topFloor.geometry} material={materials.ice_topFloor} position={[-0.993, 4.19, -25.299]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.258, 1.585, 2.035]} />
      <mesh geometry={nodes.ice_side.geometry} material={materials.ice_side} position={[-0.997, 3.564, -28.111]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.954, 1.58, 1.834]} />
      <mesh geometry={nodes.ice_floor.geometry} material={materials.ice_floor} position={[-0.572, 1.108, -28.053]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[1.993, 1, 1]} />
      <mesh geometry={nodes.Untitled55_20260621055359.geometry} material={materials.Untitled55_20260621055359} position={[0.816, 1.522, -29.906]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.546} />
      <mesh geometry={nodes.Untitled55_20260621055359001.geometry} material={materials.Untitled55_20260621055359} position={[-0.514, 1.468, -28.138]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.364} />
      <mesh geometry={nodes.ice_orange_stool.geometry} material={materials.ice_orange_stool} position={[-0.438, 1.263, -29.584]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.718} />
      <mesh geometry={nodes.ice_orange_stool001.geometry} material={materials.ice_orange_stool} position={[0.675, 1.249, -29.525]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.83} />
      <mesh geometry={nodes.ice_orange_stool002.geometry} material={materials.ice_orange_stool} position={[0.836, 1.269, -28.065]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.83} />
      <mesh geometry={nodes.ice_orange_stool003.geometry} material={materials.ice_orange_stool} position={[-0.623, 1.269, -28.45]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.721} />
      <mesh geometry={nodes.ice_blue_stool.geometry} material={materials.ice_blue_stool} position={[0.845, 1.294, -28.833]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.884} />
      <mesh geometry={nodes.ice_blue_stool001.geometry} material={materials.ice_blue_stool} position={[0.684, 1.27, -30.207]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.884} />
      <mesh geometry={nodes.ice_table.geometry} material={materials.ice_table} position={[-0.565, 1.386, -28.138]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.816} />
      <mesh geometry={nodes.ice_table001.geometry} material={materials.ice_table} position={[-0.339, 1.451, -29.204]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.973} />
      <mesh geometry={nodes.ice_table002.geometry} material={materials.ice_table} position={[0.91, 1.427, -28.417]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.973} />
      <mesh geometry={nodes.ice_table003.geometry} material={materials.ice_table} position={[0.765, 1.415, -29.841]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.973} />
      <mesh geometry={nodes.ice_menu.geometry} material={materials.ice_menu} position={[-0.931, 2.29, -28.514]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.898} />
      <mesh geometry={nodes.ice_menu001.geometry} material={materials.ice_menu} position={[-0.931, 1.819, -28.514]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.898} />
      <mesh geometry={nodes.ice_vending.geometry} material={materials.ice_vending} position={[-0.242, 1.61, -27.609]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.248, 1.248, 1.489]} />
      <mesh geometry={nodes.ice_name.geometry} material={materials.ice_name} position={[-0.025, 1.993, -28.061]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.037} />
      <mesh geometry={nodes.ice_blue.geometry} material={materials.ice_blue} position={[-0.558, 2.978, -27.681]} rotation={[Math.PI / 2, 1.28, -Math.PI / 2]} scale={[1.28, 1, 1.543]} />
      <mesh geometry={nodes.ice_blue001.geometry} material={materials.ice_blue} position={[-0.558, 2.994, -27.917]} rotation={[Math.PI / 2, 1.256, -Math.PI / 2]} scale={[1.28, 1, 1.543]} />
      <mesh geometry={nodes.ice_blue002.geometry} material={materials.ice_blue} position={[-0.375, 2.956, -28.167]} rotation={[Math.PI / 2, 1.215, -Math.PI / 2]} scale={[1.28, 0.471, 1.07]} />
      <mesh geometry={nodes.ice_blue003.geometry} material={materials.ice_blue} position={[-0.375, 2.987, -29.173]} rotation={[Math.PI / 2, 1.21, -Math.PI / 2]} scale={[1.28, 0.471, 1.07]} />
      <mesh geometry={nodes.ice_blue004.geometry} material={materials.ice_blue} position={[-0.557, 3.025, -28.922]} rotation={[Math.PI / 2, 1.25, -Math.PI / 2]} scale={[1.28, 1, 1.543]} />
      <mesh geometry={nodes.ice_blue005.geometry} material={materials.ice_blue} position={[-0.558, 3.009, -28.686]} rotation={[Math.PI / 2, 1.275, -Math.PI / 2]} scale={[1.28, 1, 1.543]} />
      <mesh geometry={nodes.ice_blue006.geometry} material={materials.ice_blue} position={[-0.375, 2.971, -28.421]} rotation={[Math.PI / 2, 1.215, -Math.PI / 2]} scale={[1.28, 0.471, 1.07]} />
      <mesh geometry={nodes.ice_blue007.geometry} material={materials.ice_blue} position={[-0.81, 3.276, -28.079]} rotation={[-3.141, -0.041, -2.542]} scale={[0.892, 0.351, 1.865]} />
      <mesh geometry={nodes.ice_blue008.geometry} material={materials.ice_blue} position={[-0.656, 3.182, -28.032]} rotation={[3.137, -0.041, -2.673]} scale={[1.28, 1, 1.94]} />
      <mesh geometry={nodes.ice_blue009.geometry} material={materials.ice_blue} position={[-0.829, 4.564, -28.073]} rotation={[-3.136, -0.041, -2.436]} scale={[1.098, 0.858, 2.141]} />
      <mesh geometry={nodes.ice_blue010.geometry} material={materials.ice_blue} position={[-0.938, 4.673, -28.124]} rotation={[-3.131, -0.04, -2.305]} scale={[0.765, 0.301, 2.059]} />
      <mesh geometry={nodes.ice_blue011.geometry} material={materials.ice_blue} position={[-0.637, 4.331, -28.502]} rotation={[Math.PI / 2, 0.979, -Math.PI / 2]} scale={[1.413, 0.404, 0.917]} />
      <mesh geometry={nodes.ice_blue012.geometry} material={materials.ice_blue} position={[-0.782, 4.4, -28.795]} rotation={[Math.PI / 2, 1.038, -Math.PI / 2]} scale={[1.413, 0.857, 1.323]} />
      <mesh geometry={nodes.ice_blue013.geometry} material={materials.ice_blue} position={[-0.778, 4.413, -29.056]} rotation={[Math.PI / 2, 1.014, -Math.PI / 2]} scale={[1.413, 0.857, 1.323]} />
      <mesh geometry={nodes.ice_blue014.geometry} material={materials.ice_blue} position={[-0.634, 4.345, -29.332]} rotation={[Math.PI / 2, 0.973, -Math.PI / 2]} scale={[1.413, 0.404, 0.917]} />
      <mesh geometry={nodes.ice_blue015.geometry} material={materials.ice_blue} position={[-0.64, 4.319, -28.222]} rotation={[Math.PI / 2, 0.979, -Math.PI / 2]} scale={[1.413, 0.404, 0.917]} />
      <mesh geometry={nodes.ice_blue016.geometry} material={materials.ice_blue} position={[-0.785, 4.387, -27.946]} rotation={[Math.PI / 2, 1.019, -Math.PI / 2]} scale={[1.413, 0.857, 1.323]} />
      <mesh geometry={nodes.ice_blue017.geometry} material={materials.ice_blue} position={[-0.788, 4.374, -27.685]} rotation={[Math.PI / 2, 1.043, -Math.PI / 2]} scale={[1.413, 0.857, 1.323]} />
      <mesh geometry={nodes.ice_side001.geometry} material={materials.ice_side} position={[-0.526, 1.97, -27.231]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.245, 1.758, 1.927]} />
      <mesh geometry={nodes.ice_side002.geometry} material={materials.ice_side} position={[-0.526, 1.97, -28.834]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.245, 1.758, 1.927]} />
      <mesh geometry={nodes.buildingone_back001.geometry} material={materials.buildingone43643} position={[-0.96, 1.848, -28.053]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.33, 3.735, 2.447]} />
      <mesh geometry={nodes.Untitled55_20260621055237001.geometry} material={materials['Untitled55_20260621055237.001']} position={[0.976, 1.545, -28.549]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.539} />
      <mesh geometry={nodes.Untitled55_20260621055237002.geometry} material={materials['Untitled55_20260621055237.001']} position={[-0.303, 1.545, -29.231]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.473} />
      <mesh geometry={nodes.hill.geometry} material={materials['Material.003']} position={[0, 1.064, -31.908]} scale={[1, 1, 0.274]} />
      <mesh geometry={nodes.synonyms.geometry} material={materials.synonyms} position={[-0.872, 3.132, -40.73]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.856} />
      <mesh geometry={nodes.ziplines.geometry} material={materials.ziplines} position={[-0.64, 4.928, -34.681]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.282} />
      <mesh geometry={nodes.YOU.geometry} material={materials.YOU} position={[-0.491, 3.89, -50.594]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.963} />
      <mesh geometry={nodes.LOVE.geometry} material={materials.LOVE} position={[-0.45, 4.643, -48.581]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.729} />
      <mesh geometry={nodes.nintendo_switch.geometry} material={materials.nintendo_switch} position={[-0.863, 2.213, -42.256]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.734} />
      <mesh geometry={nodes.pine.geometry} material={materials.pine} position={[-0.706, 3.023, -33.803]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.989} />
      <mesh geometry={nodes.pine001.geometry} material={materials.pine} position={[0.636, 3.094, -35.865]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.132} />
      <mesh geometry={nodes.pine002.geometry} material={materials.pine} position={[0.568, 2.44, -32.818]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.989} />
      <mesh geometry={nodes.pine003.geometry} material={materials.pine} position={[-0.183, 2.717, -36.576]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.747} />
      <mesh geometry={nodes.pine004.geometry} material={materials.pine} position={[0.38, 2.04, -38.476]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.904} />
      <mesh geometry={nodes.pine005.geometry} material={materials.pine} position={[-0.754, 2.362, -37.33]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.721} />
      <mesh geometry={nodes.pine006.geometry} material={materials.pine} position={[-0.497, 1.904, -38.851]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.904} />
      <mesh geometry={nodes.pine007.geometry} material={materials.pine} position={[-0.497, 1.158, -41.048]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.904} />
      <mesh geometry={nodes.pine008.geometry} material={materials.pine} position={[0.808, 1.449, -40.23]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.904} />
      <mesh geometry={nodes.zipline.geometry} material={materials.zipline} position={[0, 4.604, -34.84]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.565} />
      <mesh geometry={nodes.tower2.geometry} material={materials.tower2} position={[-0.019, 0.923, -42.034]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.881} />
      <mesh geometry={nodes.tower1.geometry} material={materials.tower1} position={[-0.051, 3.67, -34.889]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.767, 2.767, 3.391]} />
      <mesh geometry={nodes.loopquote.geometry} material={materials.loopquote} position={[0, 3.929, -53.949]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.752} />
      <mesh geometry={nodes.photo14.geometry} material={materials.photo14} position={[-0.737, 5.243, -36.734]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.606} />
      <mesh geometry={nodes.photo13.geometry} material={materials.photo13} position={[0, 4.457, -38.062]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.781} />
    </group>
  )
}

useGLTF.preload('/babagift_compressed.glb')
